blank_issues_enabled: false
contact_links:
  - name: Security vulnerability report
    url: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/about-coordinated-disclosure-of-security-vulnerabilities
    about: Please report security issues privately.
